### ISSUE TITLE
matchMedia tests

### ISSUE THREAD

**Issue by robflaherty** [tkadlec/Media-Query-test#2]
Hey Tim,

So I was thinking that it'd be great to extend the tests to include window.matchMedia behavior. I forked and duplicated the first test adding a matchMedia query (link below). But now that I look at it, I don't think this is actually testing anything of value. It's only testing whether a client supports matchMedia.

matchMedia is really an API for querying MQ results. I'm not sure it can have any affect on whether a browser decides to download an asset. Yeah?

But I wanted to throw the idea out there and see if you or others had any thoughts.

https://github.com/robflaherty/Media-Query-test/tree/matchmedia

**Comment by tkadlec** [comment]
Hey Rob,

Hmm, yeah—I can't think of anyway matchMedia would really affect whether a client downloads an asset or not. Your test 7 right now would report 'loaded' whenever Test 1 does—regardless of whether or not matchMedia is supported.

However, I would be interested in running some tests on matchMedia to identify any other quirks similar to what Nicholas Zakas found (http://www.nczonline.net/blog/2012/01/19/css-media-queries-in-javascript-part-2/) and in what browsers those quirks exist. That's probably for a different repo though.

**Comment by robflaherty** [comment]
Tim,

I guess I got a little ahead of myself! Agreed that there might be some interesting matchMedia things to test but that it would be a different set of tests and a different repo.
