### ISSUE TITLE
Images inside <noscript>?

### ISSUE THREAD

**Issue by evgenyneu** [tkadlec/Media-Query-test#3]
Thank you for the research. This is what I was trying to figure out for a long time. 

Another thing I really want to know is how browsers behave when:

``` HTML
<noscript><img src='image.png'/></noscript>
```

or 

``` HTML
<noscript><div id='divWithBackgroundImage'></div></noscript>
```

This case may be useful when we use JavaScript to replace images while providing fallback option for browsers without JavaScripts support.

**Comment by tkadlec** [comment]
You should be safe there. Noscript is being used in a variety of different responsive image solutions for that very reason—it doesn't result in the image being downloaded. See https://github.com/scottjehl/picturefill or an example.

**Comment by evgenyneu** [comment]
Thanks for feedback and link. This is funny you mentioned @scottjehl because it was his tweet that made me create this ticket here. Interesting how how things go round.
