### ISSUE TITLE
Using Mobile first approch

### ISSUE THREAD

**Issue by MoOx** [tkadlec/Media-Query-test#4]
Test something like that

`<img>`

display none

min-width: 601px, display true

**Comment by tkadlec** [comment]
Actually, PPK has already built a test for how browsers behave when an image is set to display:none (no media queries involved): http://www.quirksmode.org/css/displayimg.html. Unfortunately, Opera is the only browser that doesn't download the image immediately.

**Comment by MoOx** [comment]
OH that's just horrible. And Using a background when only if min-width > 600px ?
