### ISSUE TITLE
Test 10 doesn't detect double download

### ISSUE THREAD

**Issue by mdmcginn** [tkadlec/Media-Query-test#8]
According to http://timkadlec.com/mq/test10.php, only one image loads (mobile.png if screen is narrow, desktop.png if screen is wide). But Chrome Developer Tools (Network tab) say that both images are loading. Which is correct? Can the scripts detect preloading?  Is this a bug with the other tests as well? See http://www.brucelawson.co.uk/2015/why-we-cant-do-real-responsive-images-with-css-or-javascript/.

**Comment by tkadlec** [comment]
It's a side effect of the way the test works. As soon as I set the src on the image object in JavaScript, it makes the request. I check the `complete` property immediately so it doesn't skew the results of the test itself but if you follow along in Network Inspector (or something similar) you see both requests.
